/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.51
 * Generated at: 2020-03-25 02:20:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.member.model.vo.Member;
import com.kh.member.model.vo.Member;

public final class boardInsertForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/board/../common/menubar.jsp", Long.valueOf(1585028241280L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	//Member loginUser = (Member)request.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"");
      out.print( request.getContextPath());
      out.write("/resources/css/boardmain.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("\t.boardInsert{\r\n");
      out.write("\t\tmargin-top:4%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.sidebar{\r\n");
      out.write("\t\tdisplay:block;\r\n");
      out.write("\t}\r\n");
      out.write("\t/* The Modal (background) */\r\n");
      out.write("    .modal {\r\n");
      out.write("        display: none; /* Hidden by default */\r\n");
      out.write("        position: fixed; /* Stay in place */\r\n");
      out.write("        z-index: 1; /* Sit on top */\r\n");
      out.write("        left: 0;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        width: 100%; /* Full width */\r\n");
      out.write("        height: 100%; /* Full height */\r\n");
      out.write("        overflow: auto; /* Enable scroll if needed */\r\n");
      out.write("        background-color: rgb(0,0,0); /* Fallback color */\r\n");
      out.write("        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Modal Content/Box */\r\n");
      out.write("    .modal-content {\r\n");
      out.write("        background-color: #fefefe;\r\n");
      out.write("        margin: 15% auto; /* 15% from the top and centered */\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border: 1px solid #888;\r\n");
      out.write("        width: 50%; /* Could be more or less, depending on screen size */                          \r\n");
      out.write("    }\r\n");
      out.write("    /* The Close Button */\r\n");
      out.write("    .close {\r\n");
      out.write("        color: #aaa;\r\n");
      out.write("        float: right;\r\n");
      out.write("        font-size: 28px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    .close:hover,\r\n");
      out.write("    .close:focus {\r\n");
      out.write("        color: black;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\t.modal-content{\r\n");
      out.write("\t\tmax-width:fit-content;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

	String contextPath = request.getContextPath();
	//String msg = (String)request.getAttribute("msg");
	Member loginUser = (Member)session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Menubar</title>\r\n");
      out.write("\t<!-- Dropdown -->\r\n");
      out.write("\t<link href=\"");
      out.print( contextPath );
      out.write("/resources/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"");
      out.print( contextPath );
      out.write("/resources/css/mainMenu.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"");
      out.print( contextPath );
      out.write("/resources/css/bootstrap-reboot.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"");
      out.print( contextPath );
      out.write("/resources/css/bootstrap-grid.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"");
      out.print( contextPath );
      out.write("/resources/css/bootstrap-grid.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"");
      out.print( contextPath );
      out.write("/resources/css/mainMenu.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"#\">\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction loginValidate(){\r\n");
      out.write("\t\tif($(\"#userId\").val().trim().length == 0){\r\n");
      out.write("\t\t\talert(\"아이디를 입력하세요\");\r\n");
      out.write("\t\t\t$(\"#userId\").focus;\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($(\"#userPwd\").val().trim().length == 0){\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력하세요\");\r\n");
      out.write("\t\t\t$(\"#userPwd\").focus;\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t.container-1{\r\n");
      out.write("  \t\twidth: 300px;\r\n");
      out.write("  \t\tvertical-align: middle;\r\n");
      out.write("  \t\twhite-space: nowrap;\r\n");
      out.write("  \t\tposition: relative;\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar fixed-top navbar-expand-lg navbar-dark bg-info fixed-top\">\r\n");
      out.write("\t\t<div class=\"container\" style=\"margin:auto; padding:10px;\">\r\n");
      out.write("\t\t\t<img alt=\"\" src=\"");
      out.print(contextPath);
      out.write("/resources/images/globe.png\" width=\"4%\" height=\"4%\"> &nbsp;&nbsp;\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"");
      out.print(contextPath );
      out.write("\">세모웹툰</a>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav\">\r\n");
      out.write("\t\t\t\t<a class=\"nav-link\" href=\"about();\" style=\"float:left;\">연재</a>\r\n");
      out.write("\t\t\t\t<div class=\"nav-link\" onclick=\"semoBoard();\" style=\"cursor:pointer;\">세모게시판</div>\t\r\n");
      out.write("      \t\t</ul>\r\n");
      out.write("      \t\t\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("        \t<!-- \r\n");
      out.write("          \t\t<li class=\"nav-item\">\r\n");
      out.write("            \t<a class=\"nav-link\" href=\"about();\" style=\"float:left;\">연재</a>\r\n");
      out.write("          \t</li>\r\n");
      out.write("          \t<li class=\"nav-item\">\r\n");
      out.write("            \t<div class=\"nav-link\" onclick=\"semoBoard();\" style=\"cursor:pointer;\">세모게시판</div>\r\n");
      out.write("          \t</li>\r\n");
      out.write("          \t-->\r\n");
      out.write("          \t<li class=\"nav-item\">\r\n");
      out.write("              \t<input id=\"searchform\" type=\"search\" name=\"search\" placeholder=\" Search work...\" class=\"container-1\" style=\"border-radius: 0.25rem; height:100%; margin:0\">\r\n");
      out.write("              \t<input id=\"searchbtn\" type=\"submit\" class=\"btn\" value=\"검색\" style=\"height:100%\">\r\n");
      out.write("          \t</li>\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          <!-- 로그인 폼 영역(dropdown) -->\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"loginArea-main\" style=\"margin:auto; margin-left:10px;\">\r\n");
      out.write("          \t");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("\t          <form id=\"loginForm-drop\" action=\"");
      out.print(contextPath);
      out.write("/login.me\" method=\"post\" onsubmit=\"return loginValidate();\">\r\n");
      out.write("\t\t          <li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t            <a class=\"nav-link dropdown-toggle btn btn-warning\" href=\"#\" id=\"test2\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">로그인</a>\r\n");
      out.write("\t\t            <div class=\"dropdown-menu dropdown-menu-center\" aria-labelledby=\"test2\" style=\"width:300px\"> \r\n");
      out.write("\t\t              <div class=\"loginArea\" id=\"loginLogo\" style=\"text-align: left;\"><b>로그인</b></div>\r\n");
      out.write("\t\t              <div class=\"loginArea\">\r\n");
      out.write("\t\t                <input type=\"text\" id=\"userId\" name=\"userId\" placeholder=\"아이디\">\r\n");
      out.write("\t\t              </div>\r\n");
      out.write("\t\t              <div class=\"loginArea\">\r\n");
      out.write("\t\t                <input type=\"password\" id=\"userPwd\" name=\"userPwd\" placeholder=\"비밀번호\">\r\n");
      out.write("\t\t              </div>\r\n");
      out.write("\t\t              <div class=\"loginArea\">\r\n");
      out.write("\t\t                <label class=\"logCheck\"> \r\n");
      out.write("\t\t                  <input type=\"checkbox\" name=\"remember_me\" >\r\n");
      out.write("\t\t                  <i>로그인 상태 유지</i>\r\n");
      out.write("\t\t                </label>\r\n");
      out.write("\t\t              </div>\r\n");
      out.write("\t\t              <div class=\"loginBtn\">\r\n");
      out.write("\t\t                <button type=\"submit\" class=\"btn btn-sm btn-outline-warning lgBtn lgbtn-major lgBtn-wide lgBtn-mid\">로그인</button>\r\n");
      out.write("\t\t              </div>\r\n");
      out.write("\t\t              <div class=\"login_links\" style=\"text-align:center\">\r\n");
      out.write("\t\t                <a id=\"member_join\" href=\"memberTerms.me\">회원가입</a>\r\n");
      out.write("\t\t                <a id=\"id_pw_find\" href=\"idpwdFind.me\">아이디/비밀번호 찾기</a>\r\n");
      out.write("\t\t              </div>\r\n");
      out.write("\t\t              <div class=\"login_driver\">\r\n");
      out.write("\t\t                <span>또는</span>\r\n");
      out.write("\t\t              </div>\r\n");
      out.write("\t\t              <button type=\"button\" class=\"account_btn account_btn-naver oauth-connect\" data-service=\"naver\">네이버로 로그인 / 가입</button>\r\n");
      out.write("\t\t              <button type=\"button\" class=\"account_btn account_btn-kakao oauth-connect\" data-service=\"kakao\">카카오로 로그인 / 가입</button>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t              <p class=\"account_help\">\r\n");
      out.write("\t\t                \"\r\n");
      out.write("\t\t                    이용 중 도움이 필요하시면 [\"\r\n");
      out.write("\t\t                <a href=\"ko/help\">고객지원</a>\r\n");
      out.write("\t\t                \"] 페이지로, 로그인에 문제가 있다면 \"\r\n");
      out.write("\t\t                <a href=\"semo:help@semo.com\">semohelp@semo.com</a>\r\n");
      out.write("\t\t                \"으로 문의해 주세요.\r\n");
      out.write("\t\t                \"\r\n");
      out.write("\t\t              </p>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t          </li>\r\n");
      out.write("\t          </form>\r\n");
      out.write("\t          ");
 } else { 
      out.write("\r\n");
      out.write("\t          <li class=\"nav-item dropdown\" style=\"padding=0\">\r\n");
      out.write("\t            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"test2\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t                <div class=\"media mt-4 comment_area2\">\r\n");
      out.write("\t                    <img class=\"userImg\" src=\"");
      out.print(contextPath);
      out.write("/resources/images/defaultIcon.png\" width=\"25px\" height=\"25px\" margin-left=\"2px\">\r\n");
      out.write("\t                    <div class=\"media-body\">\r\n");
      out.write("\t                      ");
      out.print(loginUser.getMemberName() );
      out.write("\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                  </div>\r\n");
      out.write("\t            </a>\r\n");
      out.write("\t            <div class=\"dropdown-menu dropdown-menu-center\" aria-labelledby=\"test2\"> \r\n");
      out.write("\t              <div class=\"loginArea\" id=\"loginLogo\" style=\"text-align: left;\">\r\n");
      out.write("\t              \t<img class=\"userImg\" src=\"");
      out.print(contextPath);
      out.write("/resources/images/defaultIcon.png\" width=\"25px\"\r\n");
      out.write("\t              \t height=\"25px\" margin-left=\"2px\">");
      out.print( loginUser.getMemberName() );
      out.write("\r\n");
      out.write("\t              \t <button>로그아웃</button>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t              <div class=\"myCoin\">\r\n");
      out.write("\t                  보유 코인 : ");
      out.print( loginUser.getMyCookieCount() );
      out.write("개 <button>충전하기</button>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t              \r\n");
      out.write("\t              ");
 if(loginUser != null & loginUser.getMemberId().equals("admin")) { 
      out.write("\r\n");
      out.write("\t              <div class=\"adminPgIn\">\r\n");
      out.write("\t                  <a href=\"");
      out.print(contextPath );
      out.write("/main.ad\">관리자페이지</a>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t              ");
 } else { 
      out.write("\r\n");
      out.write("\t              <div class=\"myPageIn\">\r\n");
      out.write("\t                  <a href=\"myPage.me\">마이페이지</a>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t              <div class=\"writerPgIn\">\r\n");
      out.write("\t                  <a href=\"\">작가페이지</a>\r\n");
      out.write("\t              </div>\t              \r\n");
      out.write("\t              ");
 } 
      out.write("\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t          ");
 } 
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  \r\n");
      out.write("  <script>\r\n");
      out.write("  \tfunction semoBoard(){\r\n");
      out.write("  \t\tlocation.href=\"");
      out.print( request.getContextPath() );
      out.write("/boardList.bo\";\r\n");
      out.write("  \t}\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 사이드바 -->\r\n");
      out.write("\t<div class=\"sidebar\">\r\n");
      out.write("\t\t<!-- Page Heading/Breadcrumbs -->\r\n");
      out.write("\t    <h1 class=\"mt-4 mb-3\">그림게시판\r\n");
      out.write("\t      <!-- <small>Subheading</small> -->\r\n");
      out.write("\t    </h1>\r\n");
      out.write("\t\r\n");
      out.write("\t    <ol class=\"breadcrumb\">\r\n");
      out.write("\t      <li class=\"breadcrumb-item\">\r\n");
      out.write("\t        <a href=\"Notice_공지사항.html\">세모게시판 > 웹툰 TalkTalk</a>\r\n");
      out.write("\t      </li>\r\n");
      out.write("\t    </ol>\r\n");
      out.write("\t\r\n");
      out.write("\t    <!-- Content Row -->\r\n");
      out.write("\t    <div class=\"row\">\r\n");
      out.write("\t      <!-- Sidebar Column -->\r\n");
      out.write("\t      <div class=\"col-lg-3 mb-4\">\r\n");
      out.write("\t        <div class=\"list-group\">\r\n");
      out.write("\t          <a href=\"semoBoard.html\" class=\"list-group-item\">그림게시판</a>\r\n");
      out.write("\t          <a href=\"boardList.bo\" class=\"list-group-item\">웹툰 TalkTalk</a>\r\n");
      out.write("\t          <a href=\"talkfree.html\" class=\"list-group-item\">수다수다 유머방</a>\r\n");
      out.write("        \t</div>\r\n");
      out.write("      \t  </div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"boardInsert\">\r\n");
      out.write("\t\t<table style=\"width: 600px;margoin-left: auto;margin-left: 25%;margin-top: -19%;\">\r\n");
      out.write("              <tr style=\"border-bottom:1px solid rgb(163, 160, 160);\">\r\n");
      out.write("                  <td>\r\n");
      out.write("                      <h2>웹툰TalkTalk</h2>\r\n");
      out.write("                  </td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr style=\"border:1px solid rgb(163, 160, 160); margin-top: 5px;\">\r\n");
      out.write("                  <td>\r\n");
      out.write("                      <h6>웹툰에 대해 자유롭게 얘기해보아요!</h6>\r\n");
      out.write("                  </td>\r\n");
      out.write("              </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<form id=\"insertForm\" action=\"");
      out.print(contextPath);
      out.write("/insertWebTalk.bo\" method=\"post\">\r\n");
      out.write("\t\t<table align=\"center\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"title\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>내용</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<textarea rows=\"20\" name=\"content\" style=\"resize:none;\"></textarea>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"writer\" value=\"");
      out.print( loginUser.getMemberNo() );
      out.write("\">\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"btns\" align=\"center\">\r\n");
      out.write("\t\t\t<button type=\"button\" onclick=\"location.href='boardList.bo'\">취소</button>\r\n");
      out.write("\t\t\t<button type=\"submit\">작성</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\t<!-- 모달창 -->\r\n");
      out.write("\t\t<!--\r\n");
      out.write("\t\t<button id=\"okBtn\">확인</button>\r\n");
      out.write("\t    <button id=\"cancelBtn\">취소</button>\r\n");
      out.write("\t  -->\r\n");
      out.write("\t    <!-- 모달 영역 -->\r\n");
      out.write("\t   <!--  <div id=\"myModal\" class=\"modal\"> -->\r\n");
      out.write("\t    \r\n");
      out.write("\t      <!-- 모달 내용 -->\r\n");
      out.write("\t     <!--  <div class=\"modal-content\">\r\n");
      out.write("\t        <span class=\"close\">&times;</span>                                                               \r\n");
      out.write("\t        <p>게시물을 올리시겠습니까?</p>\r\n");
      out.write("\t        <div class=\"modalBtn\">\r\n");
      out.write("\t        \t<button type=\"button\" onclick=\"location.href='boardList.bo'\">취소</button>\r\n");
      out.write("\t        \t<button type=\"button\">확인</button>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t \r\n");
      out.write("\t    </div>\r\n");
      out.write("\t     -->\r\n");
      out.write("\t    <!-- Bootstrap core JavaScript -->\r\n");
      out.write("\t\t<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t// Get the modal\r\n");
      out.write("\t    var modal = document.getElementById('myModal');\r\n");
      out.write("\t\r\n");
      out.write("\t    // Get the button that opens the modal\r\n");
      out.write("\t    var btn = document.getElementById(\"okBtn\");\r\n");
      out.write("\t\r\n");
      out.write("\t    // Get the <span> element that closes the modal\r\n");
      out.write("\t    var span = document.getElementsByClassName(\"close\")[0];                                          \r\n");
      out.write("\t\r\n");
      out.write("\t    // When the user clicks on the button, open the modal \r\n");
      out.write("\t    btn.onclick = function() {\r\n");
      out.write("\t        modal.style.display = \"block\";\r\n");
      out.write("\t    }\r\n");
      out.write("\t\r\n");
      out.write("\t    // When the user clicks on <span> (x), close the modal\r\n");
      out.write("\t    span.onclick = function() {\r\n");
      out.write("\t        modal.style.display = \"none\";\r\n");
      out.write("\t    }\r\n");
      out.write("\t\r\n");
      out.write("\t    // When the user clicks anywhere outside of the modal, close it\r\n");
      out.write("\t    window.onclick = function(event) {\r\n");
      out.write("\t        if (event.target == modal) {\r\n");
      out.write("\t            modal.style.display = \"none\";\r\n");
      out.write("\t        }\r\n");
      out.write("\t    }\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
