/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.51
 * Generated at: 2020-03-24 00:52:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.member.model.vo.Member;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/../views/common/menubar.jsp", Long.valueOf(1584982924000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("  <title>세모 웹툰</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  <link href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom styles for this template -->\r\n");
      out.write("  <link href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/modern-business.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- Navigation -->\r\n");
      out.write("\t");
      out.write('\n');
      out.write('\n');

	String contextPath = request.getContextPath();
	String msg = (String)request.getAttribute("msg");
	Member loginUser = (Member)session.getAttribute("loginUser");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Menubar</title>\n");
      out.write("\t<!-- Dropdown -->\n");
      out.write("\t<link href=\"");
      out.print( contextPath );
      out.write("/resources/css/bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("\t<link href=\"");
      out.print( contextPath );
      out.write("/resources/css/mainMenu.css\" rel=\"stylesheet\">\n");
      out.write("\t<link href=\"");
      out.print( contextPath );
      out.write("/resources/css/bootstrap-reboot.css\" rel=\"stylesheet\">\n");
      out.write("\t<link href=\"");
      out.print( contextPath );
      out.write("/resources/css/bootstrap-grid.min.css\" rel=\"stylesheet\">\n");
      out.write("\t<link href=\"");
      out.print( contextPath );
      out.write("/resources/css/bootstrap-grid.css\" rel=\"stylesheet\">\n");
      out.write("\t<link href=\"");
      out.print( contextPath );
      out.write("/resources/css/mainMenu.css\" rel=\"stylesheet\">\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"#\">\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("\t\n");
      out.write("\t<script>\n");
      out.write("\tfunction loginValidate(){\n");
      out.write("\t\tif($(\"#userId\").val().trim().length == 0){\n");
      out.write("\t\t\talert(\"아이디를 입력하세요\");\n");
      out.write("\t\t\t$(\"#userId\").focus;\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\tif($(\"#userPwd\").val().trim().length == 0){\n");
      out.write("\t\t\talert(\"비밀번호를 입력하세요\");\n");
      out.write("\t\t\t$(\"#userPwd\").focus;\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\treturn true;\n");
      out.write("\t}\n");
      out.write("\t</script>\n");
      out.write("\t<style>\n");
      out.write("\t.container-1{\n");
      out.write("  \t\twidth: 300px;\n");
      out.write("  \t\tvertical-align: middle;\n");
      out.write("  \t\twhite-space: nowrap;\n");
      out.write("  \t\tposition: relative;\n");
      out.write("\t}\n");
      out.write("\t</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<nav class=\"navbar fixed-top navbar-expand-lg navbar-dark bg-info fixed-top\">\n");
      out.write("\t\t<div class=\"container\" style=\"margin:auto; padding:10px;\">\n");
      out.write("\t\t\t<img alt=\"\" src=\"");
      out.print(contextPath);
      out.write("/resources/images/globe.png\" width=\"4%\" height=\"4%\"> &nbsp;&nbsp;\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"");
      out.print(contextPath );
      out.write("\">세모웹툰</a>\n");
      out.write("\t\t\t<button class=\"navbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("\t\t\t</button>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t<ul class=\"navbar-nav\">\n");
      out.write("\t\t\t\t<a class=\"nav-link\" href=\"about();\" style=\"float:left;\">연재</a>\n");
      out.write("\t\t\t\t<div class=\"nav-link\" onclick=\"semoBoard();\" style=\"cursor:pointer;\">세모게시판</div>\t\n");
      out.write("      \t\t</ul>\n");
      out.write("      \t\t\n");
      out.write("\t\t\t<ul class=\"navbar-nav ml-auto\">\n");
      out.write("        \t<!-- \n");
      out.write("          \t\t<li class=\"nav-item\">\n");
      out.write("            \t<a class=\"nav-link\" href=\"about();\" style=\"float:left;\">연재</a>\n");
      out.write("          \t</li>\n");
      out.write("          \t<li class=\"nav-item\">\n");
      out.write("            \t<div class=\"nav-link\" onclick=\"semoBoard();\" style=\"cursor:pointer;\">세모게시판</div>\n");
      out.write("          \t</li>\n");
      out.write("          \t-->\n");
      out.write("          \t<li class=\"nav-item\">\n");
      out.write("              \t<input id=\"searchform\" type=\"search\" name=\"search\" placeholder=\" Search work...\" class=\"container-1\" style=\"border-radius: 0.25rem; height:100%; margin:0\">\n");
      out.write("              \t<input id=\"searchbtn\" type=\"submit\" class=\"btn\" value=\"검색\" style=\"height:100%\">\n");
      out.write("          \t</li>\n");
      out.write("          \n");
      out.write("          \n");
      out.write("          \n");
      out.write("          <!-- 로그인 폼 영역(dropdown) -->\n");
      out.write("          \n");
      out.write("          <div class=\"loginArea-main\" style=\"margin:auto; margin-left:10px;\">\n");
      out.write("          \t");
 if(loginUser == null) { 
      out.write("\n");
      out.write("\t          <form id=\"loginForm-drop\" action=\"");
      out.print(contextPath);
      out.write("/login.me\" method=\"post\" onsubmit=\"return loginValidate();\">\n");
      out.write("\t\t          <li class=\"nav-item dropdown\">\n");
      out.write("\t\t            <a class=\"nav-link dropdown-toggle btn btn-warning\" href=\"#\" id=\"test2\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">로그인</a>\n");
      out.write("\t\t            <div class=\"dropdown-menu dropdown-menu-center\" aria-labelledby=\"test2\" style=\"width:300px\"> \n");
      out.write("\t\t              <div class=\"loginArea\" id=\"loginLogo\" style=\"text-align: left;\"><b>로그인</b></div>\n");
      out.write("\t\t              <div class=\"loginArea\">\n");
      out.write("\t\t                <input type=\"text\" id=\"userId\" name=\"userId\" placeholder=\"아이디\">\n");
      out.write("\t\t              </div>\n");
      out.write("\t\t              <div class=\"loginArea\">\n");
      out.write("\t\t                <input type=\"password\" id=\"userPwd\" name=\"userPwd\" placeholder=\"비밀번호\">\n");
      out.write("\t\t              </div>\n");
      out.write("\t\t              <div class=\"loginArea\">\n");
      out.write("\t\t                <label class=\"logCheck\"> \n");
      out.write("\t\t                  <input type=\"checkbox\" name=\"remember_me\" >\n");
      out.write("\t\t                  <i>로그인 상태 유지</i>\n");
      out.write("\t\t                </label>\n");
      out.write("\t\t              </div>\n");
      out.write("\t\t              <div class=\"loginBtn\">\n");
      out.write("\t\t                <button type=\"submit\" class=\"btn btn-sm btn-outline-warning lgBtn lgbtn-major lgBtn-wide lgBtn-mid\">로그인</button>\n");
      out.write("\t\t              </div>\n");
      out.write("\t\t              <div class=\"login_links\" style=\"text-align:center\">\n");
      out.write("\t\t                <a id=\"member_join\" href=\"member_join.html\">회원가입</a>\n");
      out.write("\t\t                <a id=\"id_pw_find\" href=\"id_pwd_find.html\">아이디/비밀번호 찾기</a>\n");
      out.write("\t\t              </div>\n");
      out.write("\t\t              <div class=\"login_driver\">\n");
      out.write("\t\t                <span>또는</span>\n");
      out.write("\t\t              </div>\n");
      out.write("\t\t              <button type=\"button\" class=\"account_btn account_btn-naver oauth-connect\" data-service=\"naver\">네이버로 로그인 / 가입</button>\n");
      out.write("\t\t              <button type=\"button\" class=\"account_btn account_btn-kakao oauth-connect\" data-service=\"kakao\">카카오로 로그인 / 가입</button>\n");
      out.write("\t\t\n");
      out.write("\t\t              <p class=\"account_help\">\n");
      out.write("\t\t                \"\n");
      out.write("\t\t                    이용 중 도움이 필요하시면 [\"\n");
      out.write("\t\t                <a href=\"ko/help\">고객지원</a>\n");
      out.write("\t\t                \"] 페이지로, 로그인에 문제가 있다면 \"\n");
      out.write("\t\t                <a href=\"semo:help@semo.com\">semohelp@semo.com</a>\n");
      out.write("\t\t                \"으로 문의해 주세요.\n");
      out.write("\t\t                \"\n");
      out.write("\t\t              </p>\n");
      out.write("\t\t            </div>\n");
      out.write("\t\t          </li>\n");
      out.write("\t          </form>\n");
      out.write("\t          ");
 } else { 
      out.write("\n");
      out.write("\t          <li class=\"nav-item dropdown\" style=\"padding=0\">\n");
      out.write("\t            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"test2\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("\t                <div class=\"media mt-4 comment_area2\">\n");
      out.write("\t                    <img class=\"userImg\" src=\"");
      out.print(contextPath);
      out.write("/resources/images/defaultIcon.png\" width=\"25px\" height=\"25px\" margin-left=\"2px\">\n");
      out.write("\t                    <div class=\"media-body\">\n");
      out.write("\t                      ");
      out.print(loginUser.getMemberName() );
      out.write("\n");
      out.write("\t                    </div>\n");
      out.write("\t                  </div>\n");
      out.write("\t            </a>\n");
      out.write("\t            <div class=\"dropdown-menu dropdown-menu-center\" aria-labelledby=\"test2\"> \n");
      out.write("\t              <div class=\"loginArea\" id=\"loginLogo\" style=\"text-align: left;\">\n");
      out.write("\t              \t<img class=\"userImg\" src=\"");
      out.print(contextPath);
      out.write("/resources/images/defaultIcon.png\" width=\"25px\"\n");
      out.write("\t              \t height=\"25px\" margin-left=\"2px\">");
      out.print( loginUser.getMemberName() );
      out.write("\n");
      out.write("\t              \t <button>로그아웃</button>\n");
      out.write("\t              </div>\n");
      out.write("\t              <div class=\"myCoin\">\n");
      out.write("\t                  보유 코인 : ");
      out.print( loginUser.getMyCookieCount() );
      out.write("개 <button>충전하기</button>\n");
      out.write("\t              </div>\n");
      out.write("\t              \n");
      out.write("\t              ");
 if(loginUser != null & loginUser.getMemberId().equals("admin")) { 
      out.write("\n");
      out.write("\t              <div class=\"adminPgIn\">\n");
      out.write("\t                  <a href=\"");
      out.print(contextPath );
      out.write("/main.ad\">관리자페이지</a>\n");
      out.write("\t              </div>\n");
      out.write("\t              ");
 } else { 
      out.write("\n");
      out.write("\t              <div class=\"myPageIn\">\n");
      out.write("\t                  <a href=\"myPage.me\">마이페이지</a>\n");
      out.write("\t              </div>\n");
      out.write("\t              <div class=\"writerPgIn\">\n");
      out.write("\t                  <a href=\"\">작가페이지</a>\n");
      out.write("\t              </div>\t              \n");
      out.write("\t              ");
 } 
      out.write("\n");
      out.write("\t            </div>\n");
      out.write("\t          </li>\n");
      out.write("\t          ");
 } 
      out.write("\n");
      out.write("          </div>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </nav>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <header>\r\n");
      out.write("    <div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("      <ol class=\"carousel-indicators\">\r\n");
      out.write("        <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("        <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"></li>\r\n");
      out.write("        <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"2\"></li>\r\n");
      out.write("      </ol>\r\n");
      out.write("      <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("        <!-- Slide One - Set the background image for this slide in the line below -->\r\n");
      out.write("        <div class=\"carousel-item active\" style=\"background-image: url('http://placehold.it/1900x1080')\">\r\n");
      out.write("          <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("            <h3>First Slide</h3>\r\n");
      out.write("            <p>This is a description for the first slide.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Slide Two - Set the background image for this slide in the line below -->\r\n");
      out.write("        <div class=\"carousel-item\" style=\"background-image: url('http://placehold.it/1900x1080')\">\r\n");
      out.write("          <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("            <h3>Second Slide</h3>\r\n");
      out.write("            <p>This is a description for the second slide.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Slide Three - Set the background image for this slide in the line below -->\r\n");
      out.write("        <div class=\"carousel-item\" style=\"background-image: url('http://placehold.it/1900x1080')\">\r\n");
      out.write("          <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("            <h3>Third Slide</h3>\r\n");
      out.write("            <p>This is a description for the third slide.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <a class=\"carousel-control-prev\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("        <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("        <span class=\"sr-only\">Previous</span>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a class=\"carousel-control-next\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("        <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("        <span class=\"sr-only\">Next</span>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("  <!-- Page Content -->\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <h1 class=\"my-4\">Welcome to Modern Business</h1>\r\n");
      out.write("\r\n");
      out.write("    <!-- Marketing Icons Section -->\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-lg-4 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <h4 class=\"card-header\">Card Title</h4>\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-primary\">Learn More</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <h4 class=\"card-header\">Card Title</h4>\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis ipsam eos, nam perspiciatis natus commodi similique totam consectetur praesentium molestiae atque exercitationem ut consequuntur, sed eveniet, magni nostrum sint fuga.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-primary\">Learn More</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 mb-4\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <h4 class=\"card-header\">Card Title</h4>\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"card-footer\">\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-primary\">Learn More</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Portfolio Section -->\r\n");
      out.write("    <h2>Portfolio Heading</h2>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-lg-4 col-sm-6 portfolio-item\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <a href=\"#\"><img class=\"card-img-top\" src=\"http://placehold.it/700x400\" alt=\"\"></a>\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">\r\n");
      out.write("              <a href=\"#\">Project One</a>\r\n");
      out.write("            </h4>\r\n");
      out.write("            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur eum quasi sapiente nesciunt? Voluptatibus sit, repellat sequi itaque deserunt, dolores in, nesciunt, illum tempora ex quae? Nihil, dolorem!</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-sm-6 portfolio-item\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <a href=\"#\"><img class=\"card-img-top\" src=\"http://placehold.it/700x400\" alt=\"\"></a>\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">\r\n");
      out.write("              <a href=\"#\">Project Two</a>\r\n");
      out.write("            </h4>\r\n");
      out.write("            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-sm-6 portfolio-item\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <a href=\"#\"><img class=\"card-img-top\" src=\"http://placehold.it/700x400\" alt=\"\"></a>\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">\r\n");
      out.write("              <a href=\"#\">Project Three</a>\r\n");
      out.write("            </h4>\r\n");
      out.write("            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos quisquam, error quod sed cumque, odio distinctio velit nostrum temporibus necessitatibus et facere atque iure perspiciatis mollitia recusandae vero vel quam!</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-sm-6 portfolio-item\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <a href=\"#\"><img class=\"card-img-top\" src=\"http://placehold.it/700x400\" alt=\"\"></a>\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">\r\n");
      out.write("              <a href=\"#\">Project Four</a>\r\n");
      out.write("            </h4>\r\n");
      out.write("            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-sm-6 portfolio-item\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <a href=\"#\"><img class=\"card-img-top\" src=\"http://placehold.it/700x400\" alt=\"\"></a>\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">\r\n");
      out.write("              <a href=\"#\">Project Five</a>\r\n");
      out.write("            </h4>\r\n");
      out.write("            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-sm-6 portfolio-item\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <a href=\"#\"><img class=\"card-img-top\" src=\"http://placehold.it/700x400\" alt=\"\"></a>\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">\r\n");
      out.write("              <a href=\"#\">Project Six</a>\r\n");
      out.write("            </h4>\r\n");
      out.write("            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque earum nostrum suscipit ducimus nihil provident, perferendis rem illo, voluptate atque, sit eius in voluptates, nemo repellat fugiat excepturi! Nemo, esse.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Features Section -->\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-lg-6\">\r\n");
      out.write("        <h2>Modern Business Features</h2>\r\n");
      out.write("        <p>The Modern Business template by Start Bootstrap includes:</p>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>\r\n");
      out.write("            <strong>Bootstrap v4</strong>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>jQuery</li>\r\n");
      out.write("          <li>Font Awesome</li>\r\n");
      out.write("          <li>Working contact form with validation</li>\r\n");
      out.write("          <li>Unstyled page elements for easy customization</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, omnis doloremque non cum id reprehenderit, quisquam totam aspernatur tempora minima unde aliquid ea culpa sunt. Reiciendis quia dolorum ducimus unde.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-6\">\r\n");
      out.write("        <img class=\"img-fluid rounded\" src=\"http://placehold.it/700x450\" alt=\"\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("    <hr>\r\n");
      out.write("\r\n");
      out.write("    <!-- Call to Action Section -->\r\n");
      out.write("    <div class=\"row mb-4\">\r\n");
      out.write("      <div class=\"col-md-8\">\r\n");
      out.write("        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <a class=\"btn btn-lg btn-secondary btn-block\" href=\"#\">Call to Action</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer -->\r\n");
      out.write("  <footer class=\"py-5 bg-dark\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <p class=\"m-0 text-center text-white\">Copyright &copy; Your Website 2019</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.container -->\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core JavaScript -->\r\n");
      out.write("  <script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
